USE KtchKhmMrtDB
GO

BEGIN TRANSACTION;

CREATE TABLE Product (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ProductCode VARCHAR(20) UNIQUE NOT NULL,
    ProductName NVARCHAR(150) NOT NULL,
    ProductCategoryId UNIQUEIDENTIFIER
);

CREATE TABLE Category (
    Id UNIQUEIDENTIFIER UNIQUE NOT NULL DEFAULT NEWSEQUENTIALID(),
    CategoryName NVARCHAR(150)
);

CREATE TABLE ProductConfig (
    Id INT IDENTITY(1,1) NOT NULL,
    ProductId UNIQUEIDENTIFIER,
    ProductConfigValue NVARCHAR(1000)  
);

CREATE TABLE GlobalConfig (
    Id INT IDENTITY(1,1) NOT NULL,
    ConfigCode VARCHAR(20) NOT NULL,
    ConfigValue NVARCHAR(250) NOT NULL
);

ROLLBACK TRANSACTION