USE KtchKhmMrtDB
GO

BEGIN TRANSACTION;

CREATE TABLE Product (
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    ProductCode VARCHAR(20) UNIQUE NOT NULL,
    ProductName NVARCHAR(150) NOT NULL,
    ProductCategoryID UNIQUEIDENTIFIER
);

CREATE TABLE Category (
    ID UNIQUEIDENTIFIER UNIQUE NOT NULL DEFAULT NEWSEQUENTIALID(),
    CategoryName NVARCHAR(150)
);

CREATE TABLE ProductConfig (
    ID INT IDENTITY(1,1) NOT NULL,
    ProductID UNIQUEIDENTIFIER,
    ProductConfigValue NVARCHAR(1000)  
);

CREATE TABLE GlobalConfig (
    ID INT IDENTITY(1,1) NOT NULL,
    ConfigCode VARCHAR(20) NOT NULL,
    ConfigValue NVARCHAR(250) NOT NULL
);

ROLLBACK TRANSACTION